import turtle

turtle.penup()
turtle.goto((0, 0))

turtle.pensize(5)
turtle.pendown()
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.penup()
turtle.hideturtle()
turtle.goto((0,0))
turtle.done()